### ISSUE TITLE
Extra Text in HTML Report

### ISSUE THREAD

**Issue by kpomservices** [Hargne/jest-html-reporter#154]
Hi 

I am getting following error message in the HTML report. with extra text like [2m, [31m etc..,

Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m

Expected: [32mtrue[39m
Received: [31mfalse[39m

----

Please help me resolve these extra characters.

Thx

**Comment by kpomservices** [comment]
Below is the output in test report html 
Expected: [32m"Exceeds maximum limit of [7m3 Form[27ms in one mail."[39m
Received: [31m"Exceeds maximum limit of [7m5 Accordion[27ms in one mail."[39m

but expected output is 
Expected: "Exceeds maximum limit of 3 Forms in one mail."
Received: "Exceeds maximum limit of 5 Accordions in one mail."

**Comment by leegee** [comment]
I've been using this module off-and-on for years, and this has *always* bugged me. `FORCE_COLORS=false jest` doesn't help...

Think I avoided it once, but I can't remember how. 

If this issue is avoidable, could it please be documented?

If this issue is unavoidable, why is that? Maybe someone can think of something....

**Comment by aga97** [comment]
check here
https://github.com/facebook/jest/issues/608#issuecomment-266390562

**Comment by leegee** [comment]
> check here [facebook/jest#608 (comment)](https://github.com/facebook/jest/issues/608#issuecomment-266390562)

Thank you very much! I was using `FORCE_COLOR=false`, but now I see `--no-color` it seems obvious! Setting env var `NO_COLOR=true` works.
