### ISSUE TITLE
Render test results fully in a <table>

### ISSUE THREAD

**Issue by MattGiesa** [Hargne/jest-html-reporter#27]
We copy/paste our test results into a Microsoft Word document for various reasons. Word is able to handle an incoming html table but each suite is not fully contained within the table - the file name and execution time are inside a div above the table. This ends up poorly formatted.

So our pasted content ends up looking like this:
<img width="667" alt="screen shot 2018-02-07 at 10 06 22 pm" src="https://user-images.githubusercontent.com/23535291/35953673-b90bde18-0c53-11e8-93c0-16a48c6b6d59.png">

I'm happy to submit a PR if this is an acceptable change.

**Comment by Hargne** [comment]
Hi,

As this is somewhat an edge-case scenario, I believe that a change of the outputted HTML would not suit the project having the theming and styling in mind.

The reason why the Word document might look a little messy is because the `lightTheme` applies `display: flex;` to the metadata container (timestamp + test result summary).

What I would suggest is either using the `defaultTheme` or create a modified stylesheet based on `lightTheme` which excludes the bits that messes up the Word document, and then point to that stylesheet via the `styleOverridePath` config option. That way you could also apply your own stylings as well!
