### ISSUE TITLE
Feature Request: Adding Test Content to HTML

### ISSUE THREAD

**Issue by sembaye** [Hargne/jest-html-reporter#36]
Hi,
it would be a handy feature if we can put additional content like return value from a Server into the HTML.

example:
```
describe('Test', () =>  {
  test('Test', (done) => {
    app.request('192.168.210.111', (err: any, cb: any) => {
      expect(err).toBe(null);
      addContent(this, {
        title: 'Received Message',
        value: cb,
      });
      done();
    });
  });
});
```
In this example you would see cb below the tested line in the HTML.
I used a similar function with the packet mochawesome.

**Comment by Hargne** [comment]
I have done some investigation into this, as I believed it to be an interesting feature, and have found a few issues that might make this tricky to implement.

First off, the example you provided above would not work (not even in mochawesome) as you are using arrow functions. From mochawesome documentation:

> Be sure to use ES5 functions and not ES6 arrow functions when using addContext to ensure this references the test object.

I believe it's important not to tie the usage of this plugin to a certain ES-version, especially since Jest is using Arrow Functions in their documentation.

However, this is not the biggest issue, but the fact that Jest have (as far as I can see) removed the usage of `this` (please see https://github.com/facebook/jest/issues/3553) which means that there is no direct way of appending to the test data output. I have done several tests, and I cannot seem to get hold of the test data either within `beforeEach`, `afterEach` or `it`/`test`.

I was able to pass the data it by assigning the `it`/`test` to a variable which was then passed into the `addContext`-method. Although that would mean that users would need to change the entire structure of their tests in order for this to work, and that is not something that I am aiming for with this plugin.

If anyone has any ideas, don't hesitate to drop a line.

**Comment by Hargne** [comment]
Closing this for now
